services:
  workstacean:
    build:
      context: .
      target: dev
    restart: unless-stopped
    env_file: .env
    environment:
      - WORKSPACE_DIR=/workspace
      - DATA_DIR=/data
    ports:
      - "8080:8080"
    volumes:
      - workspace:/workspace
      - data:/data
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
  workspace:
